const projectsData = [
  {
    projectName: "EBP Secretariat",
    continent: "North America",
    address: "777E. University Dr. Tempe, AZ 85287, United States",
    website: undefined,
    latitude: 33.4214,
    longitude: -111.9281,
    isCenter: true,
  },
  {
    projectName: "Global Invertebrates Genome Alliance (GIGA)",
    continent: "North America",
    address: "8000 North Ocean Drive Dania Beach, FL 33004, United States",
    website: "http://giga-cos.org/",
    latitude: 26.090731,
    longitude: -80.111549,
  },
  {
    projectName: "Global Ant Genome Alliance (GAGA)",
    continent: "Asia",
    address: "China National GeneBank. Address: Shenzhen 518120, China",
    website: "http://antgenomics.dk/",
    latitude: 22.5929743330096,
    longitude: 114.475597809881,
  },
  {
    projectName: "5000 Insect Genomes (i5k)",
    continent: "Asia",
    address:
      "Guangdong Province, Shenzhen, Pingshan, 金沙路西200米 邮政编码: 518122, China",
    website: "http://i5k.github.io/",
    latitude: 22.7501384972093,
    longitude: 114.396477284745,
  },
  {
    projectName: "Ag100 Pests *USDA-Agricultural Research Service",
    continent: "North America",
    address: "1400 Independence Ave. SW Washington, DC 20250, United States",
    website:
      "https://www.ars.usda.gov/news-events/news/research-news/2018/earth-biogenome-project-could-hold-solutions-for-agricultures-future/",
    latitude: 38.886960590551,
    longitude: -77.0294015895757,
  },
  {
    projectName: "10,000 Plants (10KP)",
    continent: "Asia",
    address: "China National GeneBank. Address: Shenzhen 518120, China",
    website: "https://academic.oup.com/gigascience/article/7/3/giy013/4880447",
    latitude: 22.7512392723508,
    longitude: 114.396686696391,
  },
  {
    projectName: "10,000 bird genomes (B10k)",
    continent: "Asia",
    address:
      "Building 11, Beishan Industrial Zone, Yantian District, Shenzhen 518083, China",
    website: "https://b10k.genomics.cn/",
    latitude: 22.5918312795627,
    longitude: 114.261089081046,
  },
  {
    projectName: "Genome 10K",
    continent: "North America",
    address: "1156 High St, Santa Cruz, CA 95064, United States",
    website: "https://genome10k.soe.ucsc.edu/",
    latitude: 36.9996875962649,
    longitude: -122.057616591381,
  },
  {
    projectName: "Zoonomia",
    continent: "North America",
    address: "Merkin Building 415 Main St. Cambridge, MA 02142, United States",
    website: "https://www.broadinstitute.org/200-mammals-variant-data",
    latitude: 42.3629661377069,
    longitude: -71.0887906164154,
  },
  {
    projectName: "Darwin Tree of Life (DToL)",
    continent: "Europe",
    address:
      "Wellcome Trust Genome Campus, Hinxton, Saffron Walden CB10 1RQ, United Kingdom",
    website: "https://www.darwintreeoflife.org/",
    latitude: 52.0795000649971,
    longitude: 0.184695043288939,
  },
  {
    projectName: "1000 Chilean Genomes",
    continent: "South America",
    address: "Av Alameda Libertador Bernardo O’Higgins 340, Santiago, Chile",
    website: "http://1000genomas.cl/",
    latitude: -33.4413779252253,
    longitude: -70.6405703032793,
  },
  {
    projectName: "Taiwan BioGenomes Project",
    continent: "Asia",
    address:
      "No. 128, Section 2, Academia Rd, Nangang District, Taipei City, Taiwan",
    website: undefined,
    latitude: 25.0423165399513,
    longitude: 121.616195611794,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    address:
      "Garden and Botanical Museum Berlin-Dahlem, Freie Universität Berlin, Berlin, 14195, Germany",
    website: "http://data.ggbn.org/ggbn_portal/",
    latitude: 52.4544590287757,
    longitude: 13.3056238552338,
  },
  {
    projectName: "Diversity Initiative for the Southern California Ocean",
    continent: "North America",
    address: "900 Exposition Blvd, Los Angeles, CA 90007, United States",
    website: "https://research.nhm.org/disco/",
    latitude: 34.01740738578,
    longitude: -118.288689532093,
  },
  {
    projectName: "PhyloAlps",
    continent: "Europe",
    address:
      "LECA, BP 53 Domaine Universitaire de Grenoble 2233 Rue de la Piscine 38041 Grenoble Cedex 9, France",
    website: "http://phyloalps.org/",
    latitude: 45.1937931440174,
    longitude: 5.77716508556027,
  },
  {
    projectName: "Open Green Genomes",
    continent: "North America",
    address: "1000 Independence Ave., SW Washington, DC 20585, United States",
    website:
      "https://jgi.doe.gov/csp-2018-leebens-mack-open-green-genomes-initiative/",
    latitude: 38.8866350911631,
    longitude: -77.0250830895758,
  },
  {
    projectName: "Fish10K",
    continent: "Asia",
    address:
      "Guangdong Province, Shenzhen, Pingshan, 金沙路西200米 邮政编码: 518122, China",
    website:
      "http://english.cas.cn/newsroom/research_news/life/201910/t20191008_219736.shtml",
    latitude: 22.7503462738405,
    longitude: 114.396477284745,
  },
  {
    projectName: "BRIDGE Colombia",
    continent: "South America",
    address: "Cra. 1 #18a-12, La Candelaria, Bogotá, Cundinamarca, Colombia",
    website: "http://www.bridgecolombia.org/",
    latitude: 4.60160217261602,
    longitude: -74.0661335514796,
  },
  {
    projectName: "Illinois EBP",
    continent: "North America",
    address: "1206 West Gregory Drive | MC-195 Urbana, IL 61801, United States",
    website: undefined,
    latitude: 40.1053111327455,
    longitude: -88.2247621732453,
  },
  {
    projectName: "Euglena International Network",
    continent: "Europe",
    address: "Nottingham NG7 2RD, United Kingdom",
    website: "https://euglenanetwork.wordpress.com/",
    latitude: 52.9388840823385,
    longitude: -1.19553812098056,
  },
  {
    projectName: "Catalan Initiative for the Earth BioGenome Project",
    continent: "Europe",
    address: "Carrer del Carme, 4708001 Barcelona, Spain",
    website: "https://www.scb.cat/biogenoma/en/home/",
    latitude: 41.3808991236495,
    longitude: 2.17014177004785,
  },
  {
    projectName: "Squalomix ",
    continent: "Asia",
    address: "1111 Yata, Mishima, Shizuoka 411-8540, JAPAN",
    website: "https://github.com/Squalomix/info/",
    latitude: 35.1178210867781,
    longitude: 138.938615112123,
  },
  {
    projectName: "Endemixit",
    continent: "Europe",
    address: "Via Savonarola, 9, 44121 Ferrara FE, Italy",
    website: "https://endemixit.com/",
    latitude: 44.8335754398815,
    longitude: 11.6263254702019,
  },
  {
    projectName: "Primate Genome Project",
    continent: "Asia",
    address: "866 Yuhangtang Rd, Xihu, Hangzhou, Zhejiang, 310027, China",
    website: undefined,
    latitude: 30.3131165469954,
    longitude: 120.08672252437,
  },
  {
    projectName: "Plant GARDEN",
    continent: "Asia",
    address: "2 Kazusakamatari, Kisarazu, Chiba 292-0818, Japan",
    website: "https://plantgarden.jp/en/index",
    latitude: 35.3299043082877,
    longitude: 139.990672369802,
  },
  {
    projectName: "Butterfly Genome Project",
    continent: "Asia",
    address: "E Jiaochang Rd, Wuhua District, Kunming, Yunnan, 650023, China",
    website: undefined,
    latitude: 25.0742046150302,
    longitude: 102.710641454124,
  },
  {
    projectName: "Crab Genome Project",
    continent: "Asia",
    address: "Yancheng, 224051, China",
    website: undefined,
    latitude: 39.2865459316367,
    longitude: -76.6058867760655,
  },
  {
    projectName: "Lilioid Monocots Core Group Genome Project",
    continent: "Asia",
    address: "Shaanxi, Xi'An, Beilin, 友谊西路127号 邮政编码: 710060, China",
    website: undefined,
    latitude: 34.2416950960594,
    longitude: 108.91149145442,
  },
  {
    projectName: "Cartilaginous Fish Genome Project",
    continent: "Asia",
    address:
      "127 West Youyi Road, Beilin District, Xi'an Shaanxi, 710072, China",
    website: undefined,
    latitude: 34.2412052735955,
    longitude: 108.928872912091,
  },
  {
    projectName: "Ungulates Genome Project",
    continent: "Asia",
    address: "Shaanxi, Xi'An, Beilin, 友谊西路127号 邮政编码: 710060, China",
    website: undefined,
    latitude: 34.2415797961091,
    longitude: 108.911469996749,
  },
  {
    projectName: "CanSeq150",
    continent: "North America",
    address: "686 Bay Street, Toronto, ON M5G 0A4, Canada",
    website: "http://www.cgen.ca/canseq150",
    latitude: 43.657768,
    longitude: -79.384883,
  },
  {
    projectName: "Deep-Ocean Genomes Project",
    continent: "North America",
    address: "86 Water St, Falmouth, MA 02543, United States",
    website: undefined,
    latitude: 41.5244675626808,
    longitude: -70.6709633452875,
  },
  {
    projectName: "Threatened Species Initiative",
    continent: "Australia",
    address: "Camperdown NSW 2050, Australia",
    website: "https://threatenedspeciesinitiative.com/",
    latitude: -33.8893520146476,
    longitude: 151.176609459036,
  },
  {
    projectName: "Soil Invertebrate Genome Initiative",
    continent: "Europe",
    address:
      "300 bd Sébastien Brant - BP 10413 - F-67412 Illkirch Cedex, France",
    website: undefined,
    latitude: 50.1171516011758,
    longitude: 8.65149548210233,
  },
  {
    projectName: "European Reference Genome Atlas",
    continent: "Europe",
    address: "Alfred-Kowalke-Straße 17, 10315 Berlin, Germany",
    website: "https://www.erga-biodiversity.eu/",
    latitude: 52.506110140837,
    longitude: 13.5214660552365,
  },
  {
    projectName: "Aquatic Symbiosis Genomics Project",
    continent: "Europe",
    address:
      "Wellcome Trust Genome Campus, Hinxton, Saffron Walden CB10 1RQ, United Kingdom",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    latitude: 52.0796451238228,
    longitude: 0.184780873972139,
  },
  {
    projectName: "University of CA Consortium for the EBP",
    continent: "North America",
    address: "1115 11th St, Sacramento, CA 95814, United States",
    website: undefined,
    latitude: 38.5785614673696,
    longitude: -121.492643403082,
  },
  {
    projectName: "African BioGenome Project (AfricaBP)",
    continent: "Africa",
    type: 'Headquarter',
    address:
      "Jomo Kenyatta University of Agriculture and Technology, Juja Kwale, Rd, Juja, Kenya",
    website: "http://africanbiogenome.org/",
    latitude: -1.09100401486439,
    longitude: 37.0118027267846,
  },
  {
    projectName: "African BioGenome Project (AfricaBP)",
    continent: "Africa",
    type: 'Affiliate',
    address:
      "Agricultural Research Council, Pretoria, South Africa",    
    latitude: -25.7485438,
    longitude: 28.236981,
  },
  {
    projectName: "African BioGenome Project (AfricaBP)",
    continent: "Africa",
    type: 'Affiliate',
    address:
      "Agricultural Research Council, Pretoria, South Africa",
    latitude: 9.081999,
    longitude: 8.675277,
  },
  {
    projectName: "African BioGenome Project (AfricaBP)",
    continent: "Africa",
    type: 'Affiliate',
    address:
      "Agricultural Research Council, Pretoria, South Africa",
    latitude: -33.9162159,
    longitude: 18.6044098,
  },
  {
    projectName: "African BioGenome Project (AfricaBP)",
    continent: "Africa",
    type: 'Affiliate',
    address:
      "Agricultural Research Council, Pretoria, South Africa",
    latitude: 31.791702,
    longitude: -7.09262,
  },
  {
    projectName: "Vertebrate Genomes Project",
    continent: "North America",
    address: "1230 York Ave, New York, NY 10065, United States",
    website: "https://vertebrategenomesproject.org/",
    latitude: 40.762546086418,
    longitude: -73.9561296183326,
  },
  {
    projectName: "California Conservation Genomes Project",
    continent: "North America",
    address: "31915 Mulholland Hwy, Malibu, CA 90265, United States",
    website: "https://www.ccgproject.org/",
    latitude: 34.0972216681351,
    longitude: -118.815749345584,
  },
  {
    projectName: "AusARG Reptile and Amphibian Genomics Project",
    continent: "Australia",
    address: "University of Canberra, Bruce ACT 2617 , Australia",
    website:
      "https://researchprofiles.canberra.edu.au/en/projects/ausarg-australian-amphibian-and-reptile-genomics-initiative-colla",
    latitude: -35.2379109920901,
    longitude: 149.083920042811,
  },
  {
    projectName: "Polar Genomes Project",
    continent: "Asia",
    address: "26 Songdomirae-ro, Yeonsu-gu, Incheon, South Korea",
    website: undefined,
    latitude: 37.3680463005293,
    longitude: 126.646222252692,
  },
  {
    projectName: "Dresden HQ Genomes Project",
    continent: "Europe",
    address: "Fetscherstraße 105, 01307 Dresden, Germany",
    website: undefined,
    latitude: 51.0565960135475,
    longitude: 13.7767650686559,
  },
  {
    projectName: "Epizoic Diatom Genomes Project",
    continent: "Europe",
    address: "Building F1 11 Hoffman Street Potchefstroom 2531, Norway",
    website: undefined,
    latitude: 67.290362,
    longitude: 14.564075,
  },
  {
    projectName: "Beenome100",
    continent: "North America",
    address: "1400 Independence Ave. SW Washington, DC 20250, United States",
    website: "https://www.beenome100.org/",
    latitude: 38.8869939952474,
    longitude: -77.0293264877279,
  },
  {
    projectName: "EBP-Norway",
    continent: "Europe",
    address: "Problemveien 11, 0313 Oslo, Norway",
    website: undefined,
    latitude: 59.9406157780805,
    longitude: 10.7215439556399,
  },
  {
    projectName: "Canadian BioGenome Project",
    continent: "North America",
    type: 'Headquarter',
    address: "University of British Columbia, Vancouver, BC V6T 1Z4, Canada",
    website: "https://earthbiogenome.ca/",
    latitude: 49.260125680538,
    longitude: -123.242998256668,
  },
  {
    projectName: "Canadian BioGenome Project",
    continent: "North America",
    type: "Affiliate",
    website: "https://earthbiogenome.ca/",
    latitude: 43.662536,
    longitude: -79.37189,
    },
    {
    projectName: "Canadian BioGenome Project",
    continent: "North America",
    type: "Affiliate",
    website: "https://earthbiogenome.ca/",
    latitude: 45.499981,
    longitude: -73.556587,
    },
    {
    projectName: "Canadian BioGenome Project",
    continent: "North America",
    type: "Affiliate",
    website: "https://earthbiogenome.ca/",
    latitude: 53.51485,
    longitude: -113.516594,
    },
  {
    projectName: "Plant and Fungi Trees of Life (PAFTOL)",
    continent: "Europe",
    address: "Kew, Richmond, London, TW9 3AE, United Kingdom",
    website: undefined,
    latitude: 51.4855110552546,
    longitude: -0.290697322579766,
  },
  {
    projectName: "Bat1K",
    continent: "Europe",
    address: "St Andrews KY16 9AJ, United Kingdom",
    website: "https://bat1k.com/",
    latitude: 56.3414807165955,
    longitude: -2.79448196843111,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Australia",
    address:
      "The University of Melbourne Grattan Street, Parkville Victoria, 3010, Australia",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    latitude: -37.7982102296058,
    longitude: 144.961006183392,
  },
  {
    projectName: "LOEWE Centre for Translational Biodiversity Genomics",
    continent: "Europe",
    address: "Am Jakobskirchhof 4, 99423 Weimar, Germany",
    website: "https://tbg.senckenberg.de/",
    latitude: 50.9835203315002,
    longitude: 11.3273833839938,
  },
  {
    projectName: "ATLASea",
    continent: "North America",
    address: "École normale supérieure 46, Rue d’Ulm 75005 Paris",
    website: "http://www.atlasea.fr/en/",
    latitude: 48.842107,
    longitude: 2.343990,
  },
  {
    projectName: "Ocean Genomes",
    continent: "Australia",
    address: "35 Stirling Hwy, Crawley WA 6009, Australia",
    website: undefined,
    latitude: -31.9805340353065,
    longitude: 115.819773580779,
  },
  {
    projectName: "Cetaceans Genome Project",
    continent: "North America",
    address:
      "401 Constitution Avenue NW, Room 5128 Washington, DC 20230, United States",
    website: undefined,
    latitude: 38.8914508847672,
    longitude: -77.0200468607402,
  },
  {
    projectName: "Yggdrasil",
    continent: "Europe",
    address: "Høgskoleringen 1, 7034 Trondheim, Norway",
    website: undefined,
    latitude: 63.4194157919624,
    longitude: 10.4022923711815,
  },
  {
    projectName: "Genomics of the Brazilian Biodiversity",
    continent: "South America",
    address:
      "R. Boaventura da Silva, 955 - Nazaré, Belém - PA, 66055-090, Brazil",
    website:
      "https://urldefense.com/v3/__https://www.itv.org/en/genomics-of-the-brazilian-biodiversity-gbb/__;!!IKRxdwAv5BmarQ!awfBpNjxXStAg2W86oAE-9zIWZ_y3yq2WSpBC5DA20KCtwDsYxLAWcXZfkH_S3aLYhmr9supxH1Z-ySQGVPviWD_3DqfjzbF$",
    latitude: -1.4466457631436,
    longitude: -48.4822375192399,
  },
  {
    projectName: "Project Psyche",
    continent: "Europe",
    address:
      "Wellcome Trust Genome Campus, Hinxton, Saffron Walden CB10 1RQ, United Kingdom",
    website: "https://www.projectpsyche.org/",
    latitude: 52.0811879930689,
    longitude: 0.183890380633945,
  },
  {
    projectName: "Wise Ancestors",
    continent: "North America",
    address: "Delaware Mail Stop Genomics, 2300 Delaware Ave, Santa Cruz, CA 95060",
    website:
      "https://www.wiseancestors.org/",
    latitude: 36.955401,
    longitude: -122.058069,
  },
  {
    projectName: "Hong Kong EBP",
    continent: "Asia",
    address: "The Chinese University of Hong Kong, Central Ave, Hong Kong",
    website: "http://biodiversity.sls.cuhk.edu.hk/ebphk/",
    latitude: 22.419783665852,
    longitude: 114.206728409877,
  },
  {
    projectName: "Catalan Initiative for the Earth Biogenome Project",
    continent: "Europe",
    website: "https://www.scb.cat/biogenoma/en/home/",
    address: "Andorra",
    latitude: 42.506317,
    longitude: 1.521835,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "South America",
    address: "Argentina",
    latitude: -34.603722,
    longitude: -58.381592,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Australia",
    address: "Australia",
    latitude: -35.282001,
    longitude: 149.128998,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Australia",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Australia",
    latitude: -35.282001,
    longitude: 149.128998,
    isNew: true,
  },
  {
    projectName: "i5k",
    continent: "Australia",
    website: "http://i5k.github.io/",
    address: "Australia",
    latitude: -35.282001,
    longitude: 149.128998,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    address: "Austria",
    latitude: 47.516231,
    longitude: 14.550072,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Europe",
    address: "Austria",
    latitude: 47.516231,
    longitude: 14.550072,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Austria",
    latitude: 47.516231,
    longitude: 14.550072,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Austria",
    latitude: 47.516231,
    longitude: 14.550072,
    isNew: true,
  },
  {
    projectName: "PhyloAlps",
    continent: "Europe",
    website: "http://phyloalps.org/",
    address: "Austria",
    latitude: 47.516231,
    longitude: 14.550072,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "Europe",
    website: "https://www.projectpsyche.org/",
    address: "Austria",
    latitude: 47.516231,
    longitude: 14.550072,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Asia",
    address: "Bandladesh",
    latitude: 23.810331,
    longitude: 90.412521,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    address: "Belgium",
    latitude: 50.8416,
    longitude: 4.3525,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Europe",
    website: "https://bat1k.com/",
    address: "Belgium",
    latitude: 50.8416,
    longitude: 4.3525,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Belgium",
    latitude: 50.8416,
    longitude: 4.3525,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Belgium",
    latitude: 50.8416,
    longitude: 4.3525,
    isNew: true,
  },
  {
    projectName: "Global Invertebrate Genomics Alliance",
    continent: "Europe",
    address: "Belgium",
    latitude: 50.8416,
    longitude: 4.3525,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "South America",
    website: "https://bat1k.com/",
    address: "Belize",
    latitude: 17.49952,
    longitude: -88.19756,
    isNew: true,
  },
  {
    projectName: "Wise Ancestors",
    continent: "North Amerca",
    website:
      "https://urldefense.com/v3/__http://www.wiseancestors.org__;!!IKRxdwAv5BmarQ!exbSyINIvOQTGqw9cOPQu8krsO_dXOrWXm86XJ6LORTXp3Kt2htjxXnEFMQvGDJTNOLQI1msLydDEwlw6r5SQEgbYl0$",
    address: "Bermuda",
    latitude: 32.321384,
    longitude: -64.75737,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Bosnia and Herzergovina",
    latitude: 43.85643,
    longitude: 18.413029,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "South America",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Brazil",
    latitude: -15.793889,
    longitude: -47.882778,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "South America",
    address: "Brazil",
    latitude: -15.793889,
    longitude: -47.882778,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "South America",
    website: "https://bat1k.com/",
    address: "Brazil",
    latitude: -15.793889,
    longitude: -47.882778,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "South America",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Brazil",
    latitude: -15.793889,
    longitude: -47.882778,
    isNew: true,
  },
  {
    projectName: "Global Invertebrate Genomics Alliance",
    continent: "South America",
    address: "Brazil",
    latitude: -15.793889,
    longitude: -47.882778,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Bulgaria",
    latitude: 42.7,
    longitude: 23.33,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Bulgaria",
    latitude: 42.7,
    longitude: 23.33,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "Europe",
    website: "https://www.projectpsyche.org/",
    address: "Bulgaria",
    latitude: 42.7,
    longitude: 23.33,
    isNew: true,
  },
  {
    projectName: "10KP",
    continent: "North America",
    website: "https://academic.oup.com/gigascience/article/7/3/giy013/4880447",
    address: "Canada",
    latitude: 45.424721,
    longitude: -75.695,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "North America",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Canada",
    latitude: 45.424721,
    longitude: -75.695,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "North America",
    address: "Canada",
    latitude: 45.424721,
    longitude: -75.695,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "North America",
    website: "https://bat1k.com/",
    address: "Canada",
    latitude: 45.424721,
    longitude: -75.695,
    isNew: true,
  },
  {
    projectName: "Euglena International Network",
    continent: "North America",
    website: "https://euglenanetwork.wordpress.com/",
    address: "Canada",
    latitude: 45.424721,
    longitude: -75.695,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "North America",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Canada",
    latitude: 45.424721,
    longitude: -75.695,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "North America",
    website: "https://www.projectpsyche.org/",
    address: "Canada",
    latitude: 45.424721,
    longitude: -75.695,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "South America",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Chile",
    latitude: -33.459229,
    longitude: -70.645348,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "South America",
    address: "Chile",
    latitude: -33.459229,
    longitude: -70.645348,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Asia",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "China",
    latitude: 39.9045,
    longitude: 116.391,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Asia",
    address: "China",
    latitude: 39.9045,
    longitude: 116.391,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Asia",
    website: "https://bat1k.com/",
    address: "China",
    latitude: 39.9045,
    longitude: 116.391,
    isNew: true,
  },
  {
    projectName: "EBP Hong Kong",
    continent: "Asia",
    address: "China",
    latitude: 39.9045,
    longitude: 116.391,
    isNew: true,
  },
  {
    projectName: "Euglena International Network",
    continent: "Asia",
    website: "https://euglenanetwork.wordpress.com/",
    address: "China",
    latitude: 39.9045,
    longitude: 116.391,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Asia",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "China",
    latitude: 39.9045,
    longitude: 116.391,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "South America",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Colombia",
    latitude: 4.624335,
    longitude: -74.063644,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "South America",
    address: "Colombia",
    latitude: 4.624335,
    longitude: -74.063644,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "South America",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Colombia",
    latitude: 4.624335,
    longitude: -74.063644,
    isNew: true,
  },
  {
    projectName: "Wise Ancestors",
    continent: "South America",
    website:
      "https://urldefense.com/v3/__http://www.wiseancestors.org__;!!IKRxdwAv5BmarQ!exbSyINIvOQTGqw9cOPQu8krsO_dXOrWXm86XJ6LORTXp3Kt2htjxXnEFMQvGDJTNOLQI1msLydDEwlw6r5SQEgbYl0$",
    address: "Colombia",
    latitude: 4.624335,
    longitude: -74.063644,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "North America",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Costa Rica",
    latitude: 9.92713,
    longitude: -84.082,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Africa",
    website: "https://bat1k.com/",
    address: "Côte d’Ivoire",
    latitude: 5.345317,
    longitude: -4.024429,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Croatia",
    latitude: 45.815399,
    longitude: 15.966568,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Europe",
    website: "https://bat1k.com/",
    address: "Cyprus",
    latitude: 35.16863,
    longitude: 33.36569,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Europe",
    address: "Czech Republic",
    latitude: 49.8206,
    longitude: 15.4784,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Europe",
    website: "https://bat1k.com/",
    address: "Czech Republic",
    latitude: 49.8206,
    longitude: 15.4784,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Czech Republic",
    latitude: 49.8206,
    longitude: 15.4784,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Czech Republic",
    latitude: 49.8206,
    longitude: 15.4784,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "Europe",
    website: "https://www.projectpsyche.org/",
    address: "Czech Republic",
    latitude: 49.8206,
    longitude: 15.4784,
    isNew: true,
  },
  {
    projectName: "African Biogenome Project",
    continent: "Africa",
    website: "http://africanbiogenome.org/",
    address: "Democratic Republic of the Congo",
    latitude: -4.0335,
    longitude: 21.7501,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Africa",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Democratic Republic of the Congo",
    latitude: -4.0335,
    longitude: 21.7501,
    isNew: true,
  },
  {
    projectName: " Yggdrasil",
    continent: "Europe",
    address: "Denmark",
    latitude: 55.676098,
    longitude: "12.568337.",
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Denmark",
    latitude: 55.676098,
    longitude: "12.568337.",
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Europe",
    address: "Denmark",
    latitude: 55.676098,
    longitude: "12.568337.",
    isNew: true,
  },
  {
    projectName: "B10K",
    continent: "Europe",
    website: "https://b10k.genomics.cn/",
    address: "Denmark",
    latitude: 55.676098,
    longitude: "12.568337.",
    isNew: true,
  },
  {
    projectName: "Global Ant Genome Alliance (GAGA)",
    continent: "Europe",
    website: "http://antgenomics.dk/",
    address: "Denmark",
    latitude: 55.676098,
    longitude: "12.568337.",
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Denmark",
    latitude: 55.676098,
    longitude: "12.568337.",
    isNew: true,
  },
  {
    projectName: "The ungulate genome project",
    continent: "Europe",
    address: "Denmark",
    latitude: 55.676098,
    longitude: "12.568337.",
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "South America",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Ecuador",
    latitude: -0.180653,
    longitude: -78.467834,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "South America",
    address: "Ecuador",
    latitude: -0.180653,
    longitude: -78.467834,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "South America",
    website: "https://bat1k.com/",
    address: "Ecuador",
    latitude: -0.180653,
    longitude: -78.467834,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "South America",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Ecuador",
    latitude: -0.180653,
    longitude: -78.467834,
    isNew: true,
  },
  {
    projectName: "African Biogenome Project",
    continent: "Africa",
    website: "http://africanbiogenome.org/",
    address: "Egypt",
    latitude: 30.033333,
    longitude: 31.233334,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Estonia",
    latitude: 59.436962,
    longitude: 24.753574,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "Europe",
    website: "https://www.projectpsyche.org/",
    address: "Estonia",
    latitude: 59.436962,
    longitude: 24.753574,
    isNew: true,
  },
  {
    projectName: "African Biogenome Project",
    continent: "Africa",
    website: "http://africanbiogenome.org/",
    address: "Ethiopia",
    latitude: 9.005401,
    longitude: 38.763611,
    isNew: true,
  },
  {
    projectName: " Yggdrasil",
    continent: "Europe",
    address: "Faroe Islands",
    latitude: 61.904461,
    longitude: -6.888534,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Oceania",
    address: "Fiji",
    latitude: -18.1416,
    longitude: 178.441895,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Europe",
    website: "https://bat1k.com/",
    address: "Finland",
    latitude: 60.215898,
    longitude: 25.037079,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Finland",
    latitude: 60.215898,
    longitude: 25.037079,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Finland",
    latitude: 60.215898,
    longitude: 25.037079,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "Europe",
    website: "https://www.projectpsyche.org/",
    address: "Finland",
    latitude: 60.215898,
    longitude: 25.037079,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "France",
    latitude: 48.86,
    longitude: 2.35,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Europe",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "France",
    latitude: 48.86,
    longitude: 2.35,
    isNew: true,
  },
  {
    projectName: "ATLASea",
    continent: "Europe",
    website: "http://www.atlasea.fr/en/",
    address: "France",
    latitude: 48.86,
    longitude: 2.35,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Europe",
    website: "https://bat1k.com/",
    address: "France",
    latitude: 48.86,
    longitude: 2.35,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "France",
    latitude: 48.86,
    longitude: 2.35,
    isNew: true,
  },
  {
    projectName: "Catalan Initiative for the Earth Biogenome Project",
    continent: "Europe",
    website: "https://www.scb.cat/biogenoma/en/home/",
    address: "France",
    latitude: 48.86,
    longitude: 2.35,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "France",
    latitude: 48.86,
    longitude: 2.35,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "Europe",
    website: "https://www.projectpsyche.org/",
    address: "France",
    latitude: 48.86,
    longitude: 2.35,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Africa",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Georgia",
    latitude: 33.748783,
    longitude: -84.388168,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "Africa",
    website: "https://www.projectpsyche.org/",
    address: "Georgia",
    latitude: 33.748783,
    longitude: -84.388168,
    isNew: true,
  },
  {
    projectName: "10KP",
    continent: "Europe",
    website: "https://academic.oup.com/gigascience/article/7/3/giy013/4880447",
    address: "Germany",
    latitude: 52.520008,
    longitude: 13.404954,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Germany",
    latitude: 52.520008,
    longitude: 13.404954,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Europe",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "Germany",
    latitude: 52.520008,
    longitude: 13.404954,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Europe",
    website: "https://bat1k.com/",
    address: "Germany",
    latitude: 52.520008,
    longitude: 13.404954,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Germany",
    latitude: 52.520008,
    longitude: 13.404954,
    isNew: true,
  },
  {
    projectName: "Cetacean Genomes Project",
    continent: "Europe",
    address: "Germany",
    latitude: 52.520008,
    longitude: 13.404954,
    isNew: true,
  },
  {
    projectName: "i5k",
    continent: "Europe",
    website: "http://i5k.github.io/",
    address: "Germany",
    latitude: 52.520008,
    longitude: 13.404954,
    isNew: true,
  },
  {
    projectName: "Open Green Genome Project",
    continent: "Europe",
    website:
      "https://jgi.doe.gov/csp-2018-leebens-mack-open-green-genomes-initiative/",
    address: "Germany",
    latitude: 52.520008,
    longitude: 13.404954,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "Europe",
    website: "https://www.projectpsyche.org/",
    address: "Germany",
    latitude: 52.520008,
    longitude: 13.404954,
    isNew: true,
  },
  {
    projectName: "Translational Biodiversity Genomics (TBG)",
    continent: "Europe",
    address: "Germany",
    latitude: 52.520008,
    longitude: 13.404954,
    isNew: true,
  },
  {
    projectName: "African Biogenome Project",
    continent: "Africa",
    website: "http://africanbiogenome.org/",
    address: "Ghana",
    latitude: 5.614818,
    longitude: -0.205874,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Greece",
    latitude: 37.984,
    longitude: 23.728,
    isNew: true,
  },
  {
    projectName: " Yggdrasil",
    continent: "North America",
    address: "Greenland",
    latitude: 64.18347,
    longitude: -51.72157,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "South America",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Guatemala",
    latitude: 14.628434,
    longitude: -90.522713,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Hungary",
    latitude: 47.497913,
    longitude: 19.040236,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Hungary",
    latitude: 47.497913,
    longitude: 19.040236,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Hungary",
    latitude: 47.497913,
    longitude: 19.040236,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Asia",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "India",
    latitude: 28.679079,
    longitude: 77.06971,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Asia",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "India",
    latitude: 28.679079,
    longitude: 77.06971,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Asia",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "India",
    latitude: 28.679079,
    longitude: 77.06971,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Asia",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "Indonesia",
    latitude: -6.2,
    longitude: 106.816666,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Ireland",
    latitude: 53.35014,
    longitude: -6.266155,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Europe",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "Ireland",
    latitude: 53.35014,
    longitude: -6.266155,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Europe",
    website: "https://bat1k.com/",
    address: "Ireland",
    latitude: 53.35014,
    longitude: -6.266155,
    isNew: true,
  },
  {
    projectName: "Darwin Tree of Life",
    continent: "Europe",
    website: "https://www.darwintreeoflife.org/",
    address: "Ireland",
    latitude: 53.35014,
    longitude: -6.266155,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Asia",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "Israel",
    latitude: 31.771959,
    longitude: 35.217018,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Asia",
    website: "https://bat1k.com/",
    address: "Israel",
    latitude: 31.771959,
    longitude: 35.217018,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Asia",
    address: "Israel",
    latitude: 31.771959,
    longitude: 35.217018,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Asia",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Israel",
    latitude: 31.771959,
    longitude: 35.217018,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Italy",
    latitude: 41.902782,
    longitude: 12.496366,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Europe",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "Italy",
    latitude: 41.902782,
    longitude: 12.496366,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Italy",
    latitude: 41.902782,
    longitude: 12.496366,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Italy",
    latitude: 41.902782,
    longitude: 12.496366,
    isNew: true,
  },
  {
    projectName: "PhyloAlps",
    continent: "Europe",
    website: "http://phyloalps.org/",
    address: "Italy",
    latitude: 41.902782,
    longitude: 12.496366,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "Europe",
    website: "https://www.projectpsyche.org/",
    address: "Italy",
    latitude: 41.902782,
    longitude: 12.496366,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Asia",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Japan",
    latitude: 35.652832,
    longitude: 139.839478,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Asia",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "Japan",
    latitude: 35.652832,
    longitude: 139.839478,
    isNew: true,
  },
  {
    projectName: "Euglena International Network",
    continent: "Asia",
    website: "https://euglenanetwork.wordpress.com/",
    address: "Japan",
    latitude: 35.652832,
    longitude: 139.839478,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Asia",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Japan",
    latitude: 35.652832,
    longitude: 139.839478,
    isNew: true,
  },
  {
    projectName: "Open Green Genome Project",
    continent: "Asia",
    website:
      "https://jgi.doe.gov/csp-2018-leebens-mack-open-green-genomes-initiative/",
    address: "Japan",
    latitude: 35.652832,
    longitude: 139.839478,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Africa",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Jordan",
    latitude: 31.963158,
    longitude: 35.930359,
    isNew: true,
  },
  {
    projectName: "African Biogenome Project",
    continent: "Africa",
    website: "http://africanbiogenome.org/",
    address: "Madagascar",
    latitude: 18.7669,
    longitude: 46.8691,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Africa",
    website: "https://bat1k.com/",
    address: "Malawi",
    latitude: -13.2512161,
    longitude: 34.3015278,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Malta",
    latitude: 35.884445,
    longitude: 14.506944,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Oceania",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "Marshall Islands",
    latitude: 11.6040209,
    longitude: 165.3133111,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "North America",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Mexico",
    latitude: 19.432608,
    longitude: -99.133209,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "North America",
    website: "https://bat1k.com/",
    address: "Mexico",
    latitude: 19.432608,
    longitude: -99.133209,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "North America",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Mexico",
    latitude: 19.432608,
    longitude: -99.133209,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Oceania",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "Micronesia",
    latitude: 6.92713,
    longitude: 158.182,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Montenegro",
    latitude: 42.442574,
    longitude: 19.268646,
    isNew: true,
  },
  {
    projectName: "African Biogenome Project",
    continent: "Africa",
    website: "http://africanbiogenome.org/",
    address: "Morocco",
    latitude: 31.628674,
    longitude: -7.992047,
    isNew: true,
  },
  {
    projectName: "African Biogenome Project",
    continent: "Africa",
    website: "http://africanbiogenome.org/",
    address: "Namibia",
    latitude: -22.95764,
    longitude: 18.49041,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Africa",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "Namibia",
    latitude: -22.95764,
    longitude: 18.49041,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Africa",
    website: "https://bat1k.com/",
    address: "Namibia",
    latitude: -22.95764,
    longitude: 18.49041,
    isNew: true,
  },
  {
    projectName: "Open Green Genome Project",
    continent: "Africa",
    website:
      "https://jgi.doe.gov/csp-2018-leebens-mack-open-green-genomes-initiative/",
    address: "Namibia",
    latitude: -22.95764,
    longitude: 18.49041,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Asia",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Nepal",
    latitude: 27.700001,
    longitude: 85.333336,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Netherlands",
    latitude: 52.370216,
    longitude: 4.895168,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Europe",
    website: "https://bat1k.com/",
    address: "Netherlands",
    latitude: 52.370216,
    longitude: 4.895168,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "Europe",
    website: "https://www.projectpsyche.org/",
    address: "Netherlands",
    latitude: 52.370216,
    longitude: 4.895168,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Oceania",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "New Zealand",
    latitude: -36.848461,
    longitude: 174.763336,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Oceania",
    website: "https://bat1k.com/",
    address: "New Zealand",
    latitude: -36.848461,
    longitude: 174.763336,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Oceania",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "New Zealand",
    latitude: -36.848461,
    longitude: 174.763336,
    isNew: true,
  },
  {
    projectName: "Lilioid Monocots Core Group Genome projectName",
    continent: "Oceania",
    address: "New Zealand",
    latitude: -36.848461,
    longitude: 174.763336,
    isNew: true,
  },
  {
    projectName: "African Biogenome Project",
    continent: "Africa",
    website: "http://africanbiogenome.org/",
    address: "Nigeria",
    latitude: 9.072264,
    longitude: 7.491302,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Africa",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Nigeria",
    latitude: 9.072264,
    longitude: 7.491302,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Europe",
    address: "Norway",
    latitude: 59.911491,
    longitude: 10.757933,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Europe",
    address: "Norway",
    latitude: 59.911491,
    longitude: 10.757933,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Norway",
    latitude: 59.911491,
    longitude: 10.757933,
    isNew: true,
  },
  {
    projectName: "Epizoic Diatom Genomes",
    continent: "Europe",
    address: "Norway",
    latitude: 59.911491,
    longitude: 10.757933,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Norway",
    latitude: 59.911491,
    longitude: 10.757933,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Asia",
    website: "https://bat1k.com/",
    address: "Oman",
    latitude: 23.614328,
    longitude: 58.545284,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Asia",
    website: "https://bat1k.com/",
    address: "Paikstan",
    latitude: 30.375321,
    longitude: 69.345116,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "North America",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Panama",
    latitude: 8.983333,
    longitude: -79.51667,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "North America",
    address: "Panama",
    latitude: 8.983333,
    longitude: -79.51667,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "North America",
    website: "https://bat1k.com/",
    address: "Panama",
    latitude: 8.983333,
    longitude: -79.51667,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Oceania",
    website: "https://bat1k.com/",
    address: "Papua New Guinea",
    latitude: -6.314993,
    longitude: 143.95555,
    isNew: true,
  },
  {
    projectName: " Yggdrasil",
    continent: "South America",
    address: "Peru",
    latitude: -12.046374,
    longitude: -77.042793,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "South America",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Peru",
    latitude: -12.046374,
    longitude: -77.042793,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "South America",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Peru",
    latitude: -12.046374,
    longitude: -77.042793,
    isNew: true,
  },
  {
    projectName: "Global Invertebrate Genomics Alliance",
    continent: "Asia",
    address: "Philippines",
    latitude: 14.599512,
    longitude: 120.984222,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Poland",
    latitude: 52.237049,
    longitude: 21.017532,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Poland",
    latitude: 52.237049,
    longitude: 21.017532,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "Europe",
    website: "https://www.projectpsyche.org/",
    address: "Poland",
    latitude: 52.237049,
    longitude: 21.017532,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Portugal",
    latitude: 38.736946,
    longitude: -9.142685,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Europe",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "Portugal",
    latitude: 38.736946,
    longitude: -9.142685,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Portugal",
    latitude: 38.736946,
    longitude: -9.142685,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "Europe",
    website: "https://www.projectpsyche.org/",
    address: "Portugal",
    latitude: 38.736946,
    longitude: -9.142685,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Asia",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Republic of Korea",
    latitude: 37.5326,
    longitude: 127.024612,
    isNew: true,
  },
  {
    projectName: "Korea Polar Research Institute",
    continent: "Asia",
    address: "Republic of Korea",
    latitude: 37.5326,
    longitude: 127.024612,
    isNew: true,
  },
  {
    projectName: "African Biogenome Project",
    continent: "Africa",
    website: "http://africanbiogenome.org/",
    address: "Rwanda",
    latitude: -1.9437057,
    longitude: 29.8805778,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "North America",
    website: "https://bat1k.com/",
    address: "Saint Kitts and Nevis",
    latitude: 17.363747,
    longitude: -62.754593,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Asia",
    website: "https://bat1k.com/",
    address: "Singapore",
    latitude: 1.29027,
    longitude: 103.851959,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Slovakia",
    latitude: 48.148598,
    longitude: 17.107748,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Slovenia",
    latitude: 46.056946,
    longitude: 14.505751,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Europe",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "Slovenia",
    latitude: 46.056946,
    longitude: 14.505751,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Slovenia",
    latitude: 46.056946,
    longitude: 14.505751,
    isNew: true,
  },
  {
    projectName: "10KP",
    continent: "Africa",
    website: "https://academic.oup.com/gigascience/article/7/3/giy013/4880447",
    address: "South Africa",
    latitude: -33.918861,
    longitude: 18.4233,
    isNew: true,
  },
  {
    projectName: "African Biogenome Project",
    continent: "Africa",
    website: "http://africanbiogenome.org/",
    address: "South Africa",
    latitude: -33.918861,
    longitude: 18.4233,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Africa",
    address: "South Africa",
    latitude: -33.918861,
    longitude: 18.4233,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Africa",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "South Africa",
    latitude: -33.918861,
    longitude: 18.4233,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Africa",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "South Africa",
    latitude: -33.918861,
    longitude: 18.4233,
    isNew: true,
  },
  {
    projectName: "Open Green Genome Project",
    continent: "Africa",
    website:
      "https://jgi.doe.gov/csp-2018-leebens-mack-open-green-genomes-initiative/",
    address: "South Africa",
    latitude: -33.918861,
    longitude: 18.4233,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Spain",
    latitude: 40.416775,
    longitude: -3.70379,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Europe",
    address: "Spain",
    latitude: 40.416775,
    longitude: -3.70379,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Europe",
    website: "https://bat1k.com/",
    address: "Spain",
    latitude: 40.416775,
    longitude: -3.70379,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Spain",
    latitude: 40.416775,
    longitude: -3.70379,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Spain",
    latitude: 40.416775,
    longitude: -3.70379,
    isNew: true,
  },
  {
    projectName: "i5k",
    continent: "Europe",
    website: "http://i5k.github.io/",
    address: "Spain",
    latitude: 40.416775,
    longitude: -3.70379,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "Europe",
    website: "https://www.projectpsyche.org/",
    address: "Spain",
    latitude: 40.416775,
    longitude: -3.70379,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Sweden",
    latitude: 59.334591,
    longitude: 18.06324,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Europe",
    website: "https://bat1k.com/",
    address: "Sweden",
    latitude: 59.334591,
    longitude: 18.06324,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Sweden",
    latitude: 59.334591,
    longitude: 18.06324,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    address: "Sweden",
    latitude: 59.334591,
    longitude: 18.06324,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "Europe",
    website: "https://www.projectpsyche.org/",
    address: "Sweden",
    latitude: 59.334591,
    longitude: 18.06324,
    isNew: true,
  },
  {
    projectName: "Zoonomia",
    continent: "Europe",
    website: "https://www.broadinstitute.org/200-mammals-variant-data",
    address: "Sweden",
    latitude: 59.334591,
    longitude: 18.06324,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Switzerland",
    latitude: 46.204391,
    longitude: 6.143158,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Europe",
    website: "https://bat1k.com/",
    address: "Switzerland",
    latitude: 46.204391,
    longitude: 6.143158,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Switzerland",
    latitude: 46.204391,
    longitude: 6.143158,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Switzerland",
    latitude: 46.204391,
    longitude: 6.143158,
    isNew: true,
  },
  {
    projectName: "i5k",
    continent: "Europe",
    website: "http://i5k.github.io/",
    address: "Switzerland",
    latitude: 46.204391,
    longitude: 6.143158,
    isNew: true,
  },
  {
    projectName: "Open Green Genome Project",
    continent: "Europe",
    website:
      "https://jgi.doe.gov/csp-2018-leebens-mack-open-green-genomes-initiative/",
    address: "Switzerland",
    latitude: 46.204391,
    longitude: 6.143158,
    isNew: true,
  },
  {
    projectName: "PhyloAlps",
    continent: "Europe",
    website: "http://phyloalps.org/",
    address: "Switzerland",
    latitude: 46.204391,
    longitude: 6.143158,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "Europe",
    website: "https://www.projectpsyche.org/",
    address: "Switzerland",
    latitude: 46.204391,
    longitude: 6.143158,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Asia",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "Thailand",
    latitude: 13.736717,
    longitude: 100.523186,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "Asia",
    website: "https://bat1k.com/",
    address: "Thailand",
    latitude: 13.736717,
    longitude: 100.523186,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "South America",
    website: "https://bat1k.com/",
    address: "Tobago",
    latitude: 10.671067,
    longitude: -61.521206,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Oceania",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "Tonga",
    latitude: 21.1372,
    longitude: 175.2,
    isNew: true,
  },
  {
    projectName: "Bat1K ",
    continent: "South America",
    website: "https://bat1k.com/",
    address: "Trinidad",
    latitude: 10.671067,
    longitude: -61.521206,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Asia",
    address: "Türkiye",
    latitude: 39.925533,
    longitude: 32.866287,
    isNew: true,
  },
  {
    projectName: "African Biogenome Project",
    continent: "Africa",
    website: "http://africanbiogenome.org/",
    address: "Uganda",
    latitude: 0.347596,
    longitude: 32.58252,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "Ukraine",
    latitude: 50.450001,
    longitude: 30.523333,
    isNew: true,
  },
  {
    projectName: "Biodiversity Genomics Europe",
    continent: "Europe",
    address: "Ukraine",
    latitude: 50.450001,
    longitude: 30.523333,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Asia",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "United Arab Emirates",
    latitude: 24.466667,
    longitude: 54.366669,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Europe",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "United Kingdom of Great Britain",
    latitude: 51.509865,
    longitude: -0.118092,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "Europe",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "United Kingdom of Great Britain",
    latitude: 51.509865,
    longitude: -0.118092,
    isNew: true,
  },
  {
    projectName: "Cetacean Genomes Project",
    continent: "Europe",
    address: "United Kingdom of Great Britain",
    latitude: 51.509865,
    longitude: -0.118092,
    isNew: true,
  },
  {
    projectName: "i5k",
    continent: "Europe",
    website: "http://i5k.github.io/",
    address: "United Kingdom of Great Britain",
    latitude: 51.509865,
    longitude: -0.118092,
    isNew: true,
  },
  {
    projectName: "African Biogenome Project",
    continent: "Africa",
    website: "http://africanbiogenome.org/",
    address: "United Republic of Tanzania",
    latitude: 6.369,
    longitude: 34.8888,
    isNew: true,
  },
  {
    projectName: "10KP",
    continent: "North America",
    website: "https://academic.oup.com/gigascience/article/7/3/giy013/4880447",
    address: "United States of America",
    latitude: 38.889805,
    longitude: -77.009056,
    isNew: true,
  },
  {
    projectName: "Amphibian Genomics Consortium",
    continent: "North America",
    website: "https://mvs.unimelb.edu.au/amphibian-genomics-consortium",
    address: "United States of America",
    latitude: 38.889805,
    longitude: -77.009056,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "North America",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "United States of America",
    latitude: 38.889805,
    longitude: -77.009056,
    isNew: true,
  },
  {
    projectName: "Epizoic Diatom Genomes",
    continent: "North America",
    address: "United States of America",
    latitude: 38.889805,
    longitude: -77.009056,
    isNew: true,
  },
  {
    projectName: "Euglena International Network",
    continent: "North America",
    website: "https://euglenanetwork.wordpress.com/",
    address: "United States of America",
    latitude: 38.889805,
    longitude: -77.009056,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "North America",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "United States of America",
    latitude: 38.889805,
    longitude: -77.009056,
    isNew: true,
  },
  {
    projectName: "i5k",
    continent: "North America",
    website: "http://i5k.github.io/",
    address: "United States of America",
    latitude: 38.889805,
    longitude: -77.009056,
    isNew: true,
  },
  {
    projectName: "Lilioid Monocots Core Group Genome Project",
    continent: "North America",
    address: "United States of America",
    latitude: 38.889805,
    longitude: -77.009056,
    isNew: true,
  },
  {
    projectName: "Open Green Genome Project",
    continent: "North America",
    website:
      "https://jgi.doe.gov/csp-2018-leebens-mack-open-green-genomes-initiative/",
    address: "United States of America",
    latitude: 38.889805,
    longitude: -77.009056,
    isNew: true,
  },
  {
    projectName: "Project Psyche",
    continent: "North America",
    website: "https://www.projectpsyche.org/",
    address: "United States of America",
    latitude: 38.889805,
    longitude: -77.009056,
    isNew: true,
  },
  {
    projectName: "The ungulate genome project",
    continent: "North America",
    address: "United States of America",
    latitude: 38.889805,
    longitude: -77.009056,
    isNew: true,
  },
  {
    projectName: "Aquatic Symbiosis Genomics",
    continent: "Asia",
    website:
      "https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/",
    address: "Vietnam",
    latitude: 21.028511,
    longitude: 105.804817,
    isNew: true,
  },
  {
    projectName: "Global Genome Biodiversity Network",
    continent: "Asia",
    website: "http://data.ggbn.org/ggbn_portal/",
    address: "Vietnam",
    latitude: 21.028511,
    longitude: 105.804817,
    isNew: true,
  },
];
